#!/bin/bash

[[ -n "$1" ]] && IN=$1 || exit 1;
[[ -n "$2" ]] && OUT=$2 || exit 1;
[[ -z "$FPS" ]] && FPS=25;
[[ -z "$sound" ]] && sound=0;
[[ -z "$recode" ]] && recode=0;
[[ -z "$bitrate" ]] && bitrate=800;

[[ -n "$user_passwd" ]] && IN=`echo $IN | sed  "s/rtsp:\/\//rtsp:\/\/$user_passwd\@/g"`

[[ $sound -eq 1 ]] && audio="-c:a libmp3lame -ac 1 -ar 22050 -b:a 64k" || audio="-an";
[[ $recode -eq 1 ]] && vcodec="-c:v flv -b:v ${bitrate}k" || vcodec='-c:v copy';

nice -n 20 avconv -rtsp_transport tcp -n -i $IN $vcodec $audio $OUT &> /dev/null &

ret=$?
pid=$!
if [ $ret -eq 0 ]; then
    sleep 3
    [[ -d "/proc/$pid" ]] && printf $pid;
fi;


