#!/bin/bash

[[ -n "$1" ]] && IN=$1 || exit 1;
[[ -n "$2" ]] && OUT=$2 || exit 1;
[[ -z "$ramdisk_dir" ]] && exit 1;
[[ -z "$url" ]] && exit 1;
[[ -z "$FPS" ]] && FPS=15;
[[ -z "$sound" ]] && sound=0;
[[ -z "$bitrate" ]] && bitrate=800;
USERPASSWD=`echo $user_passwd | awk -F: '{print "-user "$1" -passwd " $2}'`


tmp=$ramdisk_dir/tmp/$$
[[ $sound -eq 1 ]] && audio="-oac mp3lame -lameopts mode=3 -audio-delay -5 -af lavcresample=44100,channels=1" || audio="-nosound";

/usr/bin/mencoder -quiet \
 -noskip \
 -mc 0 \
 -ovc lavc \
 -of lavf \
 -lavfopts format=flv \
 -lavcopts vcodec=flv:keyint=$FPS:vbitrate=$bitrate \
 -fps $FPS \
 -ofps $FPS \
 $audio \
 -o $OUT $USERPASSWD $IN 2> /dev/null >> $tmp &

ret=$?
pid=$!
if [ $ret -eq 0 ]; then
    trys=0
    while [[ ( -z "$(grep 'Writing header...' $tmp)" ) && ( -d "/proc/$pid" ) && ( $trys -lt 120 ) ]]; do
	sleep 0.5;
	trys=$(( $trys+1 ));
    done;
    if [[ $trys -ge 120 ]]; then
	kill -9 $pid;
	sleep 1;
    else
	[[ -d "/proc/$pid" ]] && printf $pid;
    fi
    rm -f $tmp
fi;


